version: '3.8'

services:
  kimpscan:
    image: openjdk:21-jdk-slim  # JDK 21 이미지를 사용
    container_name: kimpscan
    ports:
      - 8080:8080
    restart: always
    environment:
      - JAVA_OPTS=-Xmx400m  # Java 옵션 (메모리 설정 등)
    volumes:
      - ./build/libs/api-0.0.1-SNAPSHOT.jar:/api-0.0.1-SNAPSHOT.jar  # 로컬 JAR 파일을 컨테이너에 매핑
    command: [ "java", "-jar", "/api-0.0.1-SNAPSHOT.jar" ]  # JAR 파일 실행
    networks:
      - docker_net
    mem_limit: 500m # 최소 256MB RAM 보장

configs:
  nginx-config:
    file: "./nginx-single.conf"

networks:
  docker_net:
    driver: bridge
