version: '3.8'

services:
  db:
    image: mariadb:lts-noble
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: my-mariadb-root-password
    volumes:
      - db_data:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - docker_net
    mem_limit: 256m # 최소 256MB RAM 보장

networks:
  docker_net:
    driver: bridge

volumes:
  kafka_data:
    driver: local
  db_data:
    driver: local
