spring:
  datasource:
    url: jdbc:h2:mem:testdb      # H2 인메모리 DB URL
    driver-class-name: org.h2.Driver
    username: sa                 # 기본 사용자
    password:                    # 기본 비밀번호 (빈 값)
  h2:
    console:
      enabled: true              # H2 콘솔 활성화
      path: /h2-console          # H2 콘솔 접속 경로
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false               # 실행되는 SQL 로그 출력
    properties:
      hibernate:
        format_sql: true # SQL 포맷을 읽기 쉽게 출력
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
        flushMode: COMMIT
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/plain
    min-response-size: 1024

app:
  auth:
#    origin: "http://localhost:8080"
#    success-url: "http://localhost:8080/auth-success.html"
#    failure-url: "http://localhost:8080/auth-failure.html"
    origin: "https://clarify.kr"
    success-url: "https://clarify.kr/auth-success.html"
    failure-url: "https://clarify.kr/auth-failure.html"
  jwt:
    secret-key: "aGVsbG8td29ybGQtaGVsbG8td29ybGQtaGVsbG8td29ybGQtaGVsbG8td29ybGQ="
    access-expiration-time: 3600
    refresh-expiration-time: 3600

logging:
  level:
    root: ERROR
    org:
      hibernate:
        SQL: OFF
      springframework: WARN
