spring:
  application:
    name: api
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb      # H2 인메모리 DB URL
    driver-class-name: org.h2.Driver
    username: sa                 # 기본 사용자
    password:                    # 기본 비밀번호 (빈 값)
  jpa:
    hibernate:
      ddl-auto: create-drop      # 애플리케이션 시작 시 테이블 생성, 종료 시 삭제
    show-sql: true               # 실행되는 SQL 로그 출력
  h2:
    console:
      enabled: true              # H2 콘솔 활성화
      path: /h2-console          # H2 콘솔 접속 경로
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
server:
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/plain
    min-response-size: 1024

